@extends('layouts.landing')
@section('title','Bromovil - Conviértete en Distribuidor')
@section('content')
  @include('landing.partials.section_banner')
  @include('landing.partials.section_por_que')
  @include('landing.partials.section_esquemas')
  @include('landing.partials.section_como_funciona')
  @include('landing.partials.section_ganancias')
  @include('landing.partials.section_tienda')
  @include('landing.partials.section_mapa')
  @include('landing.partials.section_testimonios')
  @include('landing.partials.section_faq')
  @include('landing.partials.section_banner_final')

@endsection
